# This is not a module.
# This is a list of orderable hooks.
# *ALWAYS* use a named hook.
# This means that inserting between hooks will never be an issue.
rec {
  DEVICE_INIT = 100;
  AFTER_DEVICE_INIT = DEVICE_INIT + 10;
  BEFORE_DEVICE_INIT = DEVICE_INIT - 10;

  FRAMEBUFFER_INIT = DEVICE_INIT + 5;
  AFTER_FRAMEBUFFER_INIT = FRAMEBUFFER_INIT + 1;
  BEFORE_FRAMEBUFFER_INIT = FRAMEBUFFER_INIT - 1;

  NETWORK_INIT = DEVICE_INIT + 100;
  AFTER_NETWORK_INIT = NETWORK_INIT + 10;
  BEFORE_NETWORK_INIT = NETWORK_INIT - 10;

  SERVICES_INIT = NETWORK_INIT + 100;
  AFTER_SERVICES_INIT = SERVICES_INIT + 10;
  BEFORE_SERVICES_INIT = SERVICES_INIT - 10;

  READY_INIT = SERVICES_INIT + 100;
  AFTER_READY_INIT = READY_INIT + 10;
  BEFORE_READY_INIT = READY_INIT - 10;

  SWITCH_ROOT_INIT = READY_INIT + 100;
  AFTER_SWITCH_ROOT_INIT = SWITCH_ROOT_INIT + 10;
  BEFORE_SWITCH_ROOT_INIT = SWITCH_ROOT_INIT - 10;

  # Nothing should happen after SWITCH_ROOT_HAPPENING
  SWITCH_ROOT_HAPPENING = AFTER_SWITCH_ROOT_INIT + 1;
}
