# Then add our additional modules.
# Keep this list `:sort`ed.
[
  ./adb.nix
  ./beautification.nix
  ./boot-control.nix
  ./boot-initrd.nix
  ./boot.nix
  ./bootloader.nix
  ./cross-workarounds.nix
  ./devices-metadata.nix
  ./disk-image.nix
  ./documentation.nix
  ./hardware-eink.nix
  ./generated-disk-images.nix
  ./generated-filesystems.nix
  ./hardware-allwinner.nix
  ./hardware-exynos.nix
  ./hardware-generic.nix
  ./hardware-mediatek.nix
  ./hardware-qualcomm.nix
  ./hardware-ram.nix
  ./hardware-rockchip.nix
  ./hardware-screen.nix
  ./hardware-soc.nix
  ./hardware.nix
  ./initrd-base.nix
  ./initrd-boot-gui.nix
  ./initrd-fbterm.nix
  ./initrd-fail.nix
  ./initrd-firmware.nix
  ./initrd-kernel.nix
  ./initrd-logs.nix
  ./initrd-network.nix
  ./initrd-shell.nix
  ./initrd-ssh.nix
  ./initrd-usb.nix
  ./initrd-vendor.nix
  ./initrd.nix
  ./internal.nix
  ./kernel-config.nix
  ./lib.nix
  ./luks.nix
  ./mobile.nix
  ./mobile-device.nix
  ./nixpkgs.nix
  ./outputs.nix
  ./plymouth.nix
  ./quirks
  ./recovery.nix
  ./rootfs.nix
  ./shared-rootfs.nix
  ./stage-0.nix
  ./system-build.nix
  ./system-target.nix
  ./system-types.nix
  ./usb-gadget.nix
  ./zram.nix
]
