# Keep sorted, <nixpkgs> imports first.
[
  <nixpkgs/nixos/modules/misc/nixpkgs.nix>
  <nixpkgs/nixos/modules/misc/assertions.nix>
  ./boot-initrd.nix
  ./hardware-generic.nix
  ./hardware-qualcomm.nix
  ./hardware-ram.nix
  ./hardware-screen.nix
  ./hardware-soc.nix
  ./initrd-base.nix
  ./initrd-devices.nix
  ./initrd-framebuffer.nix
  ./initrd-loop.nix
  ./initrd-nc-shell.nix
  ./initrd-network.nix
  ./initrd-splash-late.nix
  ./initrd-splash.nix
  ./initrd-ssh.nix
  ./initrd-telnet.nix
  ./mobile-device.nix
  ./quirks-qualcomm.nix
  ./system-build.nix
  ./system-types.nix
]
