= Contributing to Mobile NixOS

You don't need to write code to help contributing with Mobile NixOS.

As Mobile NixOS is a superset on top of NixOS, you should read the link:https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md[
contributing guidelines] of the NixOS project. Many of the points apply just
the same with Mobile NixOS.


== Opening issues

Issues you face when using or working with Mobile NixOS should be filed on
link:https://github.com/mobile-nixos/mobile-nixos/issues[the project's issue tracker].

First verify an existing, open, and recent issue matching your exact problem
doesn't already exist. In case of doubt, always open a new issue. Sometimes
vaguely reported symptoms are from different sources and it is easier to manage
when different issues are opened.

When describing the issues you face, please provide the most information you
can. For sharing logs, please share them as link:https://gist.github.com/[Gists]
so the issue does not get bogged down.

== Porting

ifdef::env-github[]
See the <<doc/porting-guide.adoc#,Device Porting Guide>>.
endif::[]
ifndef::env-github[]
See the <<porting-guide.adoc#,Device Porting Guide>>.
endif::[]

Once a port has been made for a new device, link:https://github.com/mobile-nixos/mobile-nixos/pulls[open a Pull Request].

== Packaging software

Unless it is related to the abstraction of device specifics, packaging should
be done upstream at the link:https://github.com/NixOS/nixpkgs[Nixpkgs] project.

Mobile NixOS is a superset of NixOS, all the software that is in NixOS is
available for Mobile NixOS.
