= Pine64 PinePhone
include::_support/common.inc[]

== Device-specific notes

=== Building a full disk image

This platform uses the `u-boot` system-type. This means that a full disk image
can be produced, and this full disk image flashed _outright_ to the block
device. That block device can be the internal eMMC or the SD card.

The PinePhone will boot from SD card if a bootloader can be found. This means
that the full disk image can be flashed to an SD card, and it will prioritise
booting it.

```
 $ nix-build --argstr device pine64-pinephone -A build.disk-image
 $ dd if=result of=/dev/mmcblkX bs=8M oflag=sync,direct status=progress
```

=== Building the boot partition

Building the full disk image may require a native AArch64 system.

The boot partition can be built, and then flashed on top of an existing Mobile
NixOS boot partition.

```
 $ nix-build --argstr device pine64-pinephone -A build.boot-partition
 $ dd if=result/mobile-nixos-boot.img of=/dev/mmcblkXp3 bs=8M oflag=sync,direct status=progress
```

=== Building U-Boot

Mobile NixOS is not managing platform firmware builds anymore.

We recommend installing link:https://tow-boot.org/[Tow-Boot] to dedicated storage
(mmcboot).

=== Building a full disk image with custom rootfs (Using a pre-built `system.img`)

The rootfs that is found as the second partition in the full disk image is only the most bare version of NixOS and is unusable in this case.
A more complete prebuilt rootfs can be found link:https://hydra.nixos.org/job/mobile-nixos/unstable/examples-demo.aarch64-linux.rootfs[here].

Replace the second partition of the full disk image with the prebuild rootfs.
It's also possible to create a new DOS partion table on the disk and adding the boot partition with boot flag and root partition manualy.

```
 $ fdisk /dev/mmcblkX
   : o  # New dos table
   : n  # New partition (boot)
     p  # Primary partition
     1  # Partition number 1
     ⏎  # First sector (select default)
     +128M  # Set size to 128mb
   : a  # Toggle bootable
     1  # for boot partition
   : n  # New partition (root)
     p  # Primary partition
     2  # Partition number 2
     ⏎  # First sector (select default)
     ⏎  # Set size to the rest of the drive (select default)
   : w  # write changes
 # Burn boot partition, see "Building the boot partition"
 # Burn the rootfs:
 $ dd if=system.img of=/dev/mmcblkXp2 bs=8M oflag=sync,direct status=progress
```

=== Usage notes

==== LED

In the default setup, the LED has been configured to show status information.
Its colour or pattern can be used to infer the status.

During boot:

 * Green when the kernel initializes the LED driver

At any time after Linux booted:

 * The red LED will flash on panic

As it does not reset the other LED colours, it may flash green/yellow rather
than off/red. If applications customize the LED status, it may flash in other
patterns involving red.
