= Motorola Moto G5 Plus
include::_support/common.inc[]

== Device-specific notes


=== Firmware for Wi-Fi

This particular phone keeps the firmware files on a partition named
`modem`.

To make use of the Wi-Fi capabilities of this phone you will need to
make them available to the firmware derivation.

The files can be acquired through different methods. You can use an
alternate recovery like TWRP, mount the partition (identified using
`blkid`) and copy the files.

Another way is to do it using an installed Mobile NixOS system, where,
too, you mount the partition and copy them:

```
$ sudo mount -o ro /dev/disk/by-partlabel/modem /mnt
$ cp -r /mnt ./modem
$ sudo umount /mnt
```

The copy of the firmware files will be in the modem directory, in the
current working directory, ready to be referred to.

=== Touchscreen

There seem to be three distinct versions of the Synaptics DSx
touchscreen driver in the vendor kernel: one in
`drivers/input/touchscreen/synaptics_*.[ch]/`, plus two others in
subdirectories `drivers/input/touchscreen/synaptics_dsx/`

Since commit 219587de9e92a in the vendor kernel, the touchscreen is
declared in the device tree as `compatible = "synaptics,dsx-i2c"`
which corresponds to the code in
`drivers/input/touchscreen/synaptics_dsx_2.6/`, but the kernel config
options specify a weird mismash of that code and and some of the files
in the parent folder. I tried cleaning this up but it broke more than
it fixed.

The option for `CONFIG_SCREEN_OFF_GESTURES` is disabled because it is
incompatible with `CONFIG_FB`
