// Required to be included, in both adoc and md inputs.
// This `{doctitle}` replacement cannot happen at the CLI input
:title: {doctitle} — Mobile NixOS
:repo: mobile-nixos/mobile-nixos
:relative_prefix: doc
:source-highlighter: rouge
:docinfo: shared
:docinfodir: _support/
:toc: macro
:nofooter:
// IMPORTANT: Keep this file FREE FROM EMPTY LINES.
// Otherwise the header section, according to asciidoc(tor) will be ended.
// vim: ft=asciidoc
