= Getting Started
include::_support/common.inc[]

This guide assumes the user knows how to prepare their device for development
use. These instructions are device-dependent, but not specific to Mobile NixOS.

Briefly said, the device's bootloader must be unlocked, meaning that it allows
running custom-built operating system images.


== Source Code

The project is hosted under the link:https://github.com/NixOS/[NixOS organization],
as link:https://github.com/NixOS/mobile-nixos[mobile-nixos].

=== Getting the sources

Depending on your configuration, for users with a GitHub account and the proper
ssh configuration.

```
$ git clone git@github.com:NixOS/mobile-nixos.git
```

Or, for everyone else.

```
$ git clone https://github.com/NixOS/mobile-nixos.git
```

Nothing else! Everything required is self-contained.

If you're interested in testing with a device not-yet-approved, you will have
to roll up your sleeves and checkout the relevant branch for the PRs.
The link:https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally[
GitHub help article] may help.


== Compiling and Running

This is where it becomes harder to make a simple guide. These are different,
heterogeneous, hardware platforms, with different quirks, compilation steps,
and mainly, installation steps.

Fear not, look for your particular device on the <<devices/index.adoc#,devices list>>
page, will likely contain the necessary instructions.

=== Using a known-good revision

Things change, and sometimes things break. This is even more true with Mobile
NixOS as the project depends on another moving target, NixOS.

You can look at the
link:https://hydra.nixos.org/job/mobile-nixos/unstable/tested/latest-finished#tabs-buildinputs[latest successful build's inputs]
to see which _revisions_ were used for a successful build.

You can then clone Nixpkgs somewhere, checkout that commit ID, and refer to it
using `NIX_PATH`. The following is only an example of how one would do this.

```
$ cd ~/Projects/
$ git clone https://github.com/NixOS/nixpkgs.git
$ cd nixpkgs
$ git checkout $revision
$ cd ~/Projects/mobile-nixos/
$ export NIX_PATH="nixpkgs=$HOME/Projects/nixpkgs"
$ nix-build [...]
```

== Customizing

You probably will want to toggle options and such things when fiddling with
Mobile NixOS, at first. The repository is structured in a way to allow you to
add options to an untracked `local.nix` file. The default `nix-build`
invocations will respect the content of that file as your configuration.

A sample `local.nix`.

```nix
{ lib, ... }:

{
  # Disables splash screens during boot
  mobile.boot.stage-1.splash.enable = false;
}
```

As Mobile NixOS is a superset on top of NixOS, all NixOS options can be used in
this configuration file, though take note that most NixOS options will only
affect the stage-2 (rootfs, system.img) build.

The <<options/index.adoc#,Options list>> page will be useful, as it provides an
overview of all the Mobile NixOS specific options.


== Using in your system configuration

As the Mobile NixOS configuration may include fixes and quirks for your device,
it is useful to include its configuration into your system's
`configuration.nix`.

Assuming your `NIX_PATH` includes `mobile-nixos=/path/to/mobile-nixos` you can
import the Mobile NixOS configuration for your device by doing the following.

```nix
# configuration.nix
{
  # "xxx-yyy" is your device "Identifier" from https://mobile.nixos.org/devices,
  # e.g. "google-marlin".
  imports = [
    (import <mobile-nixos/lib/configuration.nix> { device = "xxx-yyy"; })
    # ...
  ];

  # ...
  # Other configurations...
  # ...
}
```

While it is possible, it is discouraged to directly import the configuration
files from the `examples` directories. They may change in ways breaking your
system configuration. It is recommended to copy and edit the configuration
files from the `examples` directories if you are basing your configuration off
of an example.

== Configuration via flakes

Mobile NixOS is flakes compatible, meaning you can configure it entirely using
flakes.

=== Quickstart
All devices are exported as `nixosModules` so you need to import them to setup
Mobile NixOS. For a quickstart you should use the provided helper `mobileFlake`
which simplifies the process and sets up proper cross compilation.

```nix
{
  description = "Mobile NixOS configuration";

  inputs.nixpkgs.url = "nixpkgs/nixos-unstable";
  inputs.mobile-nixos.url = "github:NixOS/mobile-nixos";

  outputs = { self, nixpkgs, mobile-nixos }:
    mobile-nixos.lib.mobileFlake {
      hostname = "ark-test";
      system = "x86_64-linux";
      modules = [
        mobile-nixos.nixosModules.uefi-x86_64
        ({
          users.users.root.password = "111111";
        })
      ];
    };
}
```

The helper creates a `nixosConfigurations` attribute with `hostname` so you
can update the system with `nixos-rebuild` but it also sets up some `packages`
attributes so you can create a flashable-zip for example for the first-time
install with `nix build .#<hostname>_<output>`. It also sets the default
package to the default output so a simple `nix build` will probably build
your desired output. You can check all available outputs with `nix flake show`.

=== Manual setup with `nixpkgs.lib.nixosSystem`
You may also manually setup the `nixosConfigurations` attribute for the flake
using the `nixpkgs.lib.nixosSystem` function. Note however that it may bring
further complication in regards to cross compilation.

```nix
{
  description = "Mobile NixOS configuration";

  inputs.nixpkgs.url = "nixpkgs/nixos-unstable";
  inputs.mobile-nixos.url = "github:NixOS/mobile-nixos";

  outputs = { self, nixpkgs, mobile-nixos }:
    nixosConfigurations.mobile = nixpkgs.lib.nixosSystem {
      system = "aarch64-linux";
      modules = [
        mobile-nixos.nixosModules.xiaomi-begonia
        ({
          users.users.root.password = "111111";
        })
      ];
    };
  };
}
```

Now you can build this configuration using `nix build .#nixosConfigurations.mobile.config.mobile.outputs.default`.
However, it may lead to an error like:
```
error: a 'aarch64-linux' with features {} is required to build ...
```
Which occurs due to missing cross compilation. You can only use an "emulated
native build" when your host NixOS is configured with `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];`.

To properly cross-compile you need to set the system attribute to your host's
system as the mobile-nixos modules correctly configure `nixpkgs.crossSystem`.
However, this makes the flake configuration dependent on the build machine which
is undesirable. For this reason the `mobileFlake` helper sets up this cross
compilation for different build hosts using the `packages` attribute.

== Contributing

This is a big topic, and not something about getting started! Though, quickly
noted, contributions are currently handled through GitHub pull requests.

If you are unable or unwilling to use GitHub for pull requests, you can e-mail
contributions, following the usual git via e-mail contribution workflow, to my
e-mail address, which you will find attached to commits I authored.

Note that there are more in-depth guides about specific contribution topics.

ifdef::env-github[]
* <<../CONTRIBUTING.adoc#,Contributing Guide>>
endif::[]
ifndef::env-github[]
* <<contributing.adoc#,Contributing Guide>>
endif::[]
* <<porting-guide.adoc#,Device Porting Guide>>

