= Razer Phone 2
include::_support/common.inc[]

== Device-specific notes

=== Display problems

The video drivers from the vendor do not support being used with the classic
framebuffer.

Only DRM (Direct Rendering Manager) is supported.

A workaround, for the time being, is to use `simplefb`. Though when the device
boots in the default system, the `simplefb` framebuffer stops working. It is
suspected that it is the video drivers switching the display to HDR that are
causing this issue.

A workaround to help with this workaround has been implemented. When booted in
the default system, the early init will reboot to recovery. In recovery mode
the kernel does not exhibit this issue.

The solution to this problem will be to properly support DRM-only workflows.

Another avenue for solving this is to fix the fbdev emulation driver for the
Qualcomm vendor tree.

Yet another is to explore using mainline. Though it is unknown if the
dual-DSI display, for which the vendor driver is unique, would work well with
the generic code working with other SDM845 devices.

=== Playing with the RGB logo

```
$ cd /sys/class/leds
$ for f in *channel*/brightness *channel*/led_current; do echo 25 > $f; done
```
