= Google Pixel 3

== Device-specific notes

- Pixel 3 is a "retro-fitted" device with dynamic partitions (vendor, system are dynamic; userdata/boot/btldr are not)
- `kernel-als` (android-linux-stable) kernel is booting
- `kernel-mainline` is building, but `mobile-nixos`'s kernel builder needs
  plumbing to build/output the DTBO.img
- TODOs are at the bottom


== Getting Started

This assumes you copy my directory strucuture / flake.nix bits
for my `bluephone` device, or are just willing to build/boot my config.

- https://github.com/colemickens/nixcfg/blob/6abe9acc21439ac587eb427889a3d83a064f3df6/hosts/bluephone/configuration.nix[configuration.nix]
- https://github.com/colemickens/nixcfg/blob/6abe9acc21439ac587eb427889a3d83a064f3df6/flake.nix#L39-L40[flake.nix inputs]
- https://github.com/colemickens/nixcfg/blob/6abe9acc21439ac587eb427889a3d83a064f3df6/flake.nix#L185-L193[flake.nix outputs]

Let's start:

1. Install this build: https://dl.google.com/dl/android/aosp/blueline-qq3a.200805.001-factory-1ba5d2c2.zip[blueline-qq3a.200805.001].
+
[source,bash]
----
mkdir BLUE; cd BLUE
wget -O blueline.zip 'https://dl.google.com/dl/android/aosp/blueline-qq3a.200805.001-factory-1ba5d2c2.zip'
unzip blueline.zip && rm blueline.zip
./flash-all.sh
----

2. Acquire a flashable `NIXOS_SYSTEM`.
  * Download this artifact from hydra: `mobile-nixos:unstable:examples-demo.aarch64-linux.rootfs`
  * this should be a link to: https://hydra.nixos.org/job/mobile-nixos/unstable/examples-demo.aarch64-linux.rootfs/latest/download-by-type/file/rootfs-zstd[latest] (copy this link URL to clipboard)
  * download and extract it:
+
[source,bash]
----
wget -O NIXOS_SYSTEM.img.zstd 'https://hydra.nixos.org/job/mobile-nixos/unstable/examples-demo.aarch64-linux.rootfs/latest/download-by-type/file/rootfs-zstd'
zstdcat NIXOS_SYSTEM.img.zstd > NIXOS_SYSTEM.img
----

3. Erase `userdata` partition and stick the `NIXOS_SYSTEM` partition there:
+
[source,bash]
----
fastboot erase userdata
fastboot flash userdata ./NIXOS_SYSTEM.img
----

4. Build and boot the `boot.img`:
+
[source,bash]
----
$ nix build github:colemickens/nixcfg#hosts.bluephone.bootimg
fastboot boot ./result
----

5. Once it's booted, you need to configure your local machine to get an IP 
   from the phone running RNDIS:
+
[source,bash]
----
sudo ip link set usb0 up
sudo ip addr add 172.16.42.2/24 dev usb0
sudo ip addr add brd 172.16.42.255 dev usb0
sudo ip route add 172.16.42.0/24 dev usb0
----

6. Add your sshkey because we like life to be easy: (the `root` password is `nixos`)
+
[source,bash]
----
ssh-copy-id root@172.16.42.1
----

7. Build the toplevel config and push it to the phone and activate it:
+
[source,bash]
----
remote="root@172.16.42.1"
nix build github:colemickens/nixcfg#hosts.bluephone.toplevel
toplevel="$(readlink result)"
nix copy --to "ssh://${remote}" "${toplevel}"
ssh "${remote}" "sudo bash -c \"\
  nix-env --set --profile /nix/var/nix/profiles/system ${toplevel} \
  && ${toplevel}/bin/switch-to-configuration switch\""
----

== TODO

- Investigate dynamic partitions
- Determine what other firmware needs to be put in `firmware/`
- Get WiFi working?

- add a google-bluemainline variant
- remove/replace hacky workarounds in generation selection
- compare ALS and LineageOS kernel sources and options
