= Motorola Moto G5 Plus
include::_support/common.inc[]

== Device-specific notes


=== Firmware

To use Wi-Fi (and possibly also accelerated graphics, due to a weird
startup dependency) you need to extract some non-redistributable files
from the device itself. These comprise:

* the full contents of the `modem` partition, which you should 
copy to a directory (e.g. `harpia-modem`) on your build system

* the directory tree rooted at `/etc/firmware/wlan` in the
`system` partition, which you should copy to a different directory
(e.g. `harpia-wlan`) on your build system

* the file `WCNSS_wlan_dictionary.dat` in the `persist` partition,
which is the target of a symlink `/etc/firmware/wlan/prima/WCNSS_wlan_dictionary.dat`.  

The files can be acquired through different methods - for example, you
can use `adb pull` after booting an alternate recovery like
TWRP or a running Mobile NixOS system.

Once you have the files, you can override the `firmware` derivation
to point at them when you define `config.hardware.firmware`


```
  config.hardware.firmware = [
    pkgs.wireless-regdb
    config.mobile.device.firmware.override {
      modem = ./local/harpia-modem;
      wlan = ./local/harpia-wlan;
    };
  ];
```
