= Motorola Moto G4 Play
include::_support/common.inc[]

== Device-specific notes


=== Installation and partition layout

The boot partition on this device is too small for any reasonable hope
of getting Mobile NixOS on it.  We instead rely on the "extlinux"
compatibility provided by lk2nd.

lk2nd searches the device for a partition with an
extlinux-compatible layout and boots the first it finds. The
`outputs.default` target provides a file `boot.img` which is
an image of such a fileystem. A full install of Mobile NixOS comprises installing lk2nd (if not installed already), then  writing `boot.img` and
`system.img` onto any two partitions large enough to hold them.

lk2nd searches partitions on the sd card as well as builtin storage,
so you can install Mobile NixOS without touching whatever was
previously in `system`, `userdata` etc of the builtin storage. Note
that you can't write sd card partitions using fastboot and must resort
to other methods. For example, if you have TWRP you could boot to
recovery and use adb:

```
$ # assumes sd card has previously been partitioned with boot and root
$ dd status=progress if=boot.img | adb shell -e none dd of=/dev/block/mmcblk1p1 bs=1048576
$ dd status=progress if=system.img | adb shell -e none dd of=/dev/block/mmcblk1p2 bs=1048576
```

=== Wi-Fi

This particular phone keeps some of its firmware files on a partition
named `modem`.

To make use of the Wi-Fi capabilities (and possibly also accelerated
graphics, due to a weird startup dependency) of this phone you will
need to make them available to the firmware derivation.

The files can be acquired through different methods. You can use an
alternate recovery like TWRP, mount the partition (identified using
`blkid`) and copy the files.

Another way is to do it using an installed Mobile NixOS system, where,
too, you mount the partition and copy them:

```
$ sudo mount -o ro /dev/disk/by-partlabel/modem /mnt
$ cp -r /mnt ./modem
$ sudo umount /mnt
```

Once you have the files, you can override the `firmware` derivation to
point at them when you define `config.hardware.firmware`. You may also
need to add them to `mobile.boot.stage-1.firmware`.


```
  config.hardware.firmware = [
    pkgs.wireless-regdb
    config.mobile.device.firmware.override {
      modem = ./modem;
    };
  ];
```

==== Wi-Fi issues

Some users of Motorola Harpia on other mainline Linux distributions
(see the [postmarketOS issue tracker](https://gitlab.com/postmarketOS/pmaports/-/issues/1085) report that it will not work with Wi-Fi access points on all channels
but that _it does work on channel 6_. The usual symptom is that
`wpa_supplicant` connects to the AP and authenticates but then that no
IP packets are sent, meaning DHCP fails. Attempting to configure the
device for a static IP address doesn't work either.

The fix (taken from postmarketOS) is to use the wifi firmware for the
Motorola Osprey instead of the Harpia.
