= Motorola Moto G5 Plus
include::_support/common.inc[]

== Device-specific notes


=== Wi-Fi

This particular phone keeps some of its firmware files on a partition
named `modem`.

To make use of the Wi-Fi capabilities (and possibly also accelerated
graphics, due to a weird startup dependency) of this phone you will
need to make them available to the firmware derivation.

The files can be acquired through different methods. You can use an
alternate recovery like TWRP, mount the partition (identified using
`blkid`) and copy the files.

Another way is to do it using an installed Mobile NixOS system, where,
too, you mount the partition and copy them:

```
$ sudo mount -o ro /dev/disk/by-partlabel/modem /mnt
$ cp -r /mnt ./modem
$ sudo umount /mnt
```

Once you have the files, you can override the `firmware` derivation to
point at them when you define `config.hardware.firmware`. You may also
need to add them to `mobile.boot.stage-1.firmware`.


```
  config.hardware.firmware = [
    pkgs.wireless-regdb
    config.mobile.device.firmware.override {
      modem = ./modem;
    };
  ];
```

==== Wi-Fi issues

Some users of Motorola Harpia on other mainline Linux distributions
(see the [postmarketOS issue tracker](https://gitlab.com/postmarketOS/pmaports/-/issues/1085) report that it will not work with Wi-Fi access points on all channels
but that _it does work on channel 6_. The usual symptom is that
`wpa_supplicant` connects to the AP and authenticates but then that no
IP packets are sent, meaning DHCP fails. Attempting to configure the
device for a static IP address doesn't work either.

For Mobile NixOS we follow the postmarketOS lead and use the firmware
from Motorola Osprey instead of the Harpia firmware. For me this
doesn't help, and the only thing that worked was to reconfigure
my access point.  Your mileage may vary.
