= Xiaomi Redmi Note 8 Pro
include::_support/common.inc[]

== Device-specific notes

[NOTE]
====
*Do not acquire a Xiaomi Redmi Note 8 Pro with the intent to run Mobile NixOS
on it.*

This is *not* a recommended device.
====

It is of utmost importance that you read and familiarize yourself with
link:https://forum.xda-developers.com/redmi-note-8-pro/how-to/guide-redmi-note-8-pro-megathread-t4056527/post82743009[
the CFW megathread]. Not doing so *will result in a brick*.

Again, *you will almost assuredly brick your phone* unless you read, understand
and follow instructions pertaining to
https://forum.xda-developers.com/redmi-note-8-pro/how-to/guide-redmi-note-8-pro-megathread-t4056527/post82743009#post82743009[
the community CFW and the Redmi Note 8 Pro].

Finally, as a last warning, you *will need* the 
https://forum.xda-developers.com/redmi-note-8-pro/how-to/guide-redmi-note-8-pro-megathread-t4056527/post82743009#post82743009[
community CFW for the Redmi Note 8 Pro].
Otherwise *irrecoverably bricking is almost guaranteed*.


=== Recovering from a brick, quick notes

If you're told “Please select a valid authentication file or ask for
help.” it may be a red herring _as long as you were mindful of not flashing a
stock Xiaomi preloader and lk, and sticking to CFW_. Make sure you are *not*
holding power or a volume key when you plug the device in.

It is unknown what is necessary to be flashed using SP Flash Tool when
recovering a bricked device. For some bricks it seems that flashing only `boot`
is required. For other bricks it seems more is needed.


=== Fastboot commands

With the engineering preloader and aboot (lk), unknown for the stock Xiaomi
one, it is not possible to `fastboot boot` a boot image.
