name: CI
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Parse_nix:
    name: Parse .nix files
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout repository
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: "Parse .nix files"
        run: .ci/parse-all.sh
  Instantiation:
    name: Instantiation
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout repository
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: "Instantiation"
        run: |
          export NIX_PATH=nixpkgs=$PWD/pkgs.nix
          bin/hydra-eval
  Kernel_configuration_up-to-date:
    name: Kernel configuration up-to-date
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout repository
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: "Kernel configuration up-to-date"
        run: |
          export NIX_PATH=nixpkgs=$PWD/pkgs.nix
          bin/kernel-normalize-all --only-check
