name: Documentation
on:
  pull_request:
  push:
  workflow_call:

jobs:
  Documentation:
    runs-on: [ubuntu-latest]
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: "Build documentation"
        run: |
          nix-build doc

      - name: Unwrap build output
        run: |
          output=$(readlink -f result)
          cp -vr --dereference "$output" "www"

      - name: Upload archive to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'docs'
          path: 'www'
          if-no-files-found: error
